# = = = = = = =
# Elastic
# = = = = = = =
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elk
  namespace: rbc
spec:
  selector:
    matchLabels:
      app: elk-1
  template:
    metadata:
      labels:
        app: elk-1
    spec:
      containers:
        - name: elastic-kibana
          image: nshou/elasticsearch-kibana
          ports:
            - containerPort: 9200
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elk-service
  namespace: rbc
  labels:
    name: elk-1
spec:
  type: LoadBalancer
  ports:
  - name: elastic
    port: 9200
    protocol: TCP
  - name: kibana
    port: 5601
    protocol: TCP
  selector:
    app: elk-1
---
# = = = = = = =
# Kafka
# - - - - - - -
# Deployments
# - - - - - - -
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-1
  namespace: rbc
spec:
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zookeeper-1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zookeeper-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-1
  namespace: rbc
spec:
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              value: hello.world:1:1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafdrop-1
  namespace: rbc
spec:
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-service:9092"
---
# - - - - - - -
# Services
# - - - - - - -
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
  namespace: rbc
  labels:
    app: kafdrop
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 9000
      protocol: TCP
  selector:
    app: kafdrop
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: rbc
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: rbc
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka-1
    id: "0"