apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: azure-arc-data
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:

    exporters:
      kafka/laas-json:
        protocol_version: 2.0.0
        brokers: kafka-service.laas.svc:9092
        topic: otel.node.metrics.json
        encoding: otlp_json

      kafka/laas-proto:
        protocol_version: 2.0.0
        brokers: kafka-service.laas.svc:9092
        topic: otel.node.metrics.proto
        encoding: otlp_proto

    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s

    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 165

    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        metrics:
          receivers: [hostmetrics]
          processors: [memory_limiter, batch]
          exporters: [kafka/laas-json, kafka/laas-proto]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: azure-arc-data
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib:0.48.0
        name: otel-agent
        ports:
        - containerPort: 55679 # ZPages endpoint.
        - containerPort: 4317 # Default OpenTelemetry receiver port.
        - containerPort: 8888  # Metrics.
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /etc/otelcol-contrib
        - name: otel-cluster-config-vol
          mountPath: /certs
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: config.yaml
          name: otel-agent-config-vol
        - configMap:
            name: otel-cluster-config
            items:
              - key: ca.crt
                path: ca.crt
              - key: fluentbit-cert.pem
                path: fluentbit-cert.pem
              - key: fluentbit-key.pem
                path: fluentbit-key.pem
          name: otel-cluster-config-vol