# = = = = = = =
# Elastic
# = = = = = = =
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elk
  namespace: laas
spec:
  selector:
    matchLabels:
      app: elk-1
  template:
    metadata:
      labels:
        app: elk-1
    spec:
      containers:
        - name: elastic-kibana
          image: nshou/elasticsearch-kibana
          ports:
            - containerPort: 9200
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elk-service
  namespace: laas
  labels:
    name: elk-1
spec:
  type: LoadBalancer
  ports:
  - name: elastic
    port: 9200
    protocol: TCP
  - name: kibana
    port: 5601
    protocol: TCP
  selector:
    app: elk-1
---
# = = = = = = =
# Kafka
# - - - - - - -
# Deployments
# - - - - - - -
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-1
  namespace: laas
spec:
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zookeeper-1
          image: quay.io/debezium/zookeeper:1.9
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-1
  namespace: laas
spec:
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
        id: "0"
    spec:
      containers:
        - name: kafka
          image: quay.io/debezium/kafka:1.9
          ports:
            - containerPort: 9092
          env:
            # https://github.com/debezium/docker-images/blob/main/connect-base/0.3/README.md#environment-variables
            - name: ZOOKEEPER_CONNECT
              value: zookeeper-1:2181
            - name: ADVERTISED_HOST_NAME
              value: 52.226.243.196 # <- This is a hack to get things to work externally without DNS
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafdrop-1
  namespace: laas
spec:
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-service:9092"
---
# - - - - - - -
# Services
# - - - - - - -
apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
  namespace: laas
  labels:
    app: kafdrop
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 9000
      protocol: TCP
  selector:
    app: kafdrop
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: laas
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: laas
  labels:
    name: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka-1
    id: "0"